#!/usr/bin/env bash
#
# Nimbus Core — build and run the full stack in containers.
#
#   ./run.sh            build (if needed) and start
#   ./run.sh up         same
#   ./run.sh down       stop and remove containers (keeps the database volume)
#   ./run.sh rebuild    force a clean image rebuild, then start
#   ./run.sh logs       follow logs
#   ./run.sh status     show container + health state
#   ./run.sh destroy    stop and DELETE the database volume (irreversible)
#
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
BIND_ADDR="127.0.0.1"
BIND_PORT="8080"

c_red()  { printf '\033[31m%s\033[0m\n' "$*"; }
c_grn()  { printf '\033[32m%s\033[0m\n' "$*"; }
c_ylw()  { printf '\033[33m%s\033[0m\n' "$*"; }
die()    { c_red "error: $*" >&2; exit 1; }

#------------------------------------------------------------------
# Preflight
#------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH"
docker info >/dev/null 2>&1 || die "cannot talk to the docker daemon (is it running? are you in the 'docker' group?)"

if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  die "neither 'docker compose' nor 'docker-compose' is available"
fi

#------------------------------------------------------------------
# Secrets: generate a real .env on first run, never ship defaults
#------------------------------------------------------------------
gen_secret() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-48}"; }

if [[ ! -f "$ENV_FILE" ]]; then
  c_ylw "No $ENV_FILE found — generating one with fresh random secrets."

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by run.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file contains live credentials. It is gitignored — keep it that way.

POSTGRES_DB=nimbus
POSTGRES_USER=nimbus
POSTGRES_PASSWORD=$(gen_secret 48)

# HS256 signing key. Must be >= 32 bytes; rotating it invalidates all tokens.
JWT_SECRET=$(gen_secret 64)
JWT_EXPIRATION_MS=600000

# Leave empty for same-origin (correct behind the bundled nginx).
# Example for a tunnel: https://*.trycloudflare.com
APP_CORS_ALLOWED_ORIGIN_PATTERNS=
EOF
  chmod 600 "$ENV_FILE"
  c_grn "Wrote $ENV_FILE (mode 600)."
fi

chmod 600 "$ENV_FILE" 2>/dev/null || true

# Refuse to start with placeholder or too-short secrets.
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

[[ "${JWT_SECRET:-}" == *"your_jwt_secret_here"* ]] && die "JWT_SECRET is still the placeholder from .env.example"
[[ "${POSTGRES_PASSWORD:-}" == *"your_password_here"* ]] && die "POSTGRES_PASSWORD is still the placeholder from .env.example"
(( ${#JWT_SECRET} >= 32 )) || die "JWT_SECRET must be at least 32 characters (HS256); it is ${#JWT_SECRET}"
(( ${#POSTGRES_PASSWORD} >= 16 )) || die "POSTGRES_PASSWORD must be at least 16 characters; it is ${#POSTGRES_PASSWORD}"

#------------------------------------------------------------------
# Wait for the stack to report healthy
#------------------------------------------------------------------
wait_healthy() {
  local name="$1" tries="${2:-60}" cid state
  printf 'waiting for %-8s ' "$name"
  for ((i=0; i<tries; i++)); do
    cid="$("${DC[@]}" ps -q "$name" 2>/dev/null || true)"
    if [[ -n "$cid" ]]; then
      state="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid" 2>/dev/null || echo unknown)"
      case "$state" in
        healthy|running) c_grn "$state"; return 0 ;;
        exited|dead)     c_red "$state";  return 1 ;;
      esac
    fi
    printf '.'
    sleep 2
  done
  c_red "timed out"
  return 1
}

#------------------------------------------------------------------
# Commands
#------------------------------------------------------------------
cmd="${1:-up}"

case "$cmd" in
  up)
    "${DC[@]}" up -d --build
    ;;
  rebuild)
    "${DC[@]}" build --no-cache --pull
    "${DC[@]}" up -d --force-recreate
    ;;
  down)
    "${DC[@]}" down
    c_grn "Stopped. Database volume kept — './run.sh destroy' removes it."
    exit 0
    ;;
  destroy)
    c_ylw "This DELETES the database volume and every user account in it."
    read -r -p "Type 'destroy' to confirm: " ans
    [[ "$ans" == "destroy" ]] || { echo "aborted"; exit 1; }
    "${DC[@]}" down -v
    c_grn "Stack and database volume removed."
    exit 0
    ;;
  logs)
    exec "${DC[@]}" logs -f --tail=200
    ;;
  status)
    "${DC[@]}" ps
    exit 0
    ;;
  *)
    die "unknown command '$cmd' (try: up, rebuild, down, destroy, logs, status)"
    ;;
esac

echo
wait_healthy db      || { "${DC[@]}" logs --tail=40 db;      die "database did not come up"; }
wait_healthy backend || { "${DC[@]}" logs --tail=60 backend; die "backend did not come up"; }
wait_healthy web     || { "${DC[@]}" logs --tail=40 web;     die "nginx did not come up"; }

echo
c_grn "Nimbus Core is up."
echo
echo "  GUI       http://${BIND_ADDR}:${BIND_PORT}/"
echo "  API       http://${BIND_ADDR}:${BIND_PORT}/api/health"
echo
echo "  Postgres  not published — reachable only from the backend container."
echo "            shell:  ${DC[*]} exec db psql -U \$POSTGRES_USER -d \$POSTGRES_DB"
echo
echo "  logs      ./run.sh logs"
echo "  stop      ./run.sh down"
echo

# Prove the API is actually answering through nginx.
if command -v curl >/dev/null 2>&1; then
  printf 'smoke test: GET /api/health ... '
  if curl -fsS --max-time 5 "http://${BIND_ADDR}:${BIND_PORT}/api/health" >/dev/null 2>&1; then
    c_grn "ok"
  else
    c_ylw "no response yet (the backend may still be warming up)"
  fi
fi
